// Mocks generated by Mockito 5.4.6 from annotations
// in thirty_sec_challenge/test/widget/challenge_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:thirty_sec_challenge/core/network/api_response.dart' as _i2;
import 'package:thirty_sec_challenge/features/challenge/data/challenge_repository.dart'
    as _i4;
import 'package:thirty_sec_challenge/features/challenge/domain/challenge.dart'
    as _i3;
import 'package:thirty_sec_challenge/features/challenge/domain/submission.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedResponse_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResponse<T> {
  _FakePaginatedResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChallenge_1 extends _i1.SmartFake implements _i3.Challenge {
  _FakeChallenge_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChallengeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChallengeRepository extends _i1.Mock
    implements _i4.ChallengeRepository {
  MockChallengeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Challenge?> getCurrentChallenge() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentChallenge,
          [],
        ),
        returnValue: _i5.Future<_i3.Challenge?>.value(),
      ) as _i5.Future<_i3.Challenge?>);

  @override
  _i5.Future<List<_i3.Challenge>> getUpcoming() => (super.noSuchMethod(
        Invocation.method(
          #getUpcoming,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Challenge>>.value(<_i3.Challenge>[]),
      ) as _i5.Future<List<_i3.Challenge>>);

  @override
  _i5.Future<_i2.PaginatedResponse<_i3.Challenge>> getHistory({
    int? page = 1,
    int? limit = 20,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [],
          {
            #page: page,
            #limit: limit,
            #category: category,
          },
        ),
        returnValue: _i5.Future<_i2.PaginatedResponse<_i3.Challenge>>.value(
            _FakePaginatedResponse_0<_i3.Challenge>(
          this,
          Invocation.method(
            #getHistory,
            [],
            {
              #page: page,
              #limit: limit,
              #category: category,
            },
          ),
        )),
      ) as _i5.Future<_i2.PaginatedResponse<_i3.Challenge>>);

  @override
  _i5.Future<_i3.Challenge> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Challenge>.value(_FakeChallenge_1(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Challenge>);

  @override
  _i5.Future<_i2.PaginatedResponse<_i6.Submission>> getResults(
    String? challengeId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResults,
          [challengeId],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<_i2.PaginatedResponse<_i6.Submission>>.value(
            _FakePaginatedResponse_0<_i6.Submission>(
          this,
          Invocation.method(
            #getResults,
            [challengeId],
            {
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i5.Future<_i2.PaginatedResponse<_i6.Submission>>);
}
