// Mocks generated by Mockito 5.4.6 from annotations
// in thirty_sec_challenge/test/widget/feed_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:thirty_sec_challenge/core/network/api_response.dart' as _i2;
import 'package:thirty_sec_challenge/features/challenge/domain/submission.dart'
    as _i5;
import 'package:thirty_sec_challenge/features/feed/domain/repositories/feed_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedResponse_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResponse<T> {
  _FakePaginatedResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FeedRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRepository extends _i1.Mock implements _i3.FeedRepository {
  MockFeedRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Submission>> getTrending({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrending,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i5.Submission>>.value(<_i5.Submission>[]),
      ) as _i4.Future<List<_i5.Submission>>);

  @override
  _i4.Future<_i2.PaginatedResponse<_i5.Submission>> getSubmissions({
    int? page = 1,
    int? limit = 20,
    String? category,
    String? search,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubmissions,
          [],
          {
            #page: page,
            #limit: limit,
            #category: category,
            #search: search,
          },
        ),
        returnValue: _i4.Future<_i2.PaginatedResponse<_i5.Submission>>.value(
            _FakePaginatedResponse_0<_i5.Submission>(
          this,
          Invocation.method(
            #getSubmissions,
            [],
            {
              #page: page,
              #limit: limit,
              #category: category,
              #search: search,
            },
          ),
        )),
      ) as _i4.Future<_i2.PaginatedResponse<_i5.Submission>>);
}
