// Mocks generated by Mockito 5.4.6 from annotations
// in thirty_sec_challenge/test/widget/leaderboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:thirty_sec_challenge/core/network/api_response.dart' as _i2;
import 'package:thirty_sec_challenge/features/auth/data/datasources/auth_local_datasource.dart'
    as _i11;
import 'package:thirty_sec_challenge/features/auth/data/models/user_model.dart'
    as _i12;
import 'package:thirty_sec_challenge/features/auth/domain/entities/auth_tokens.dart'
    as _i5;
import 'package:thirty_sec_challenge/features/auth/domain/entities/user.dart'
    as _i4;
import 'package:thirty_sec_challenge/features/auth/domain/repositories/auth_repository.dart'
    as _i8;
import 'package:thirty_sec_challenge/features/auth/domain/usecases/logout_usecase.dart'
    as _i10;
import 'package:thirty_sec_challenge/features/auth/domain/usecases/social_login_usecase.dart'
    as _i9;
import 'package:thirty_sec_challenge/features/leaderboard/data/leaderboard_repository.dart'
    as _i6;
import 'package:thirty_sec_challenge/features/leaderboard/domain/leaderboard_entry.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedResponse_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResponse<T> {
  _FakePaginatedResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRank_1 extends _i1.SmartFake implements _i3.UserRank {
  _FakeUserRank_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_2 extends _i1.SmartFake implements _i4.User {
  _FakeUser_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthTokens_3 extends _i1.SmartFake implements _i5.AuthTokens {
  _FakeAuthTokens_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LeaderboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeaderboardRepository extends _i1.Mock
    implements _i6.LeaderboardRepository {
  MockLeaderboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.PaginatedResponse<_i3.LeaderboardEntry>> getLeaderboard({
    required String? challengeId,
    _i6.LeaderboardPeriod? period = _i6.LeaderboardPeriod.allTime,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaderboard,
          [],
          {
            #challengeId: challengeId,
            #period: period,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i7.Future<_i2.PaginatedResponse<_i3.LeaderboardEntry>>.value(
                _FakePaginatedResponse_0<_i3.LeaderboardEntry>(
          this,
          Invocation.method(
            #getLeaderboard,
            [],
            {
              #challengeId: challengeId,
              #period: period,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i7.Future<_i2.PaginatedResponse<_i3.LeaderboardEntry>>);

  @override
  _i7.Future<_i3.UserRank> getMyRank({required String? challengeId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyRank,
          [],
          {#challengeId: challengeId},
        ),
        returnValue: _i7.Future<_i3.UserRank>.value(_FakeUserRank_1(
          this,
          Invocation.method(
            #getMyRank,
            [],
            {#challengeId: challengeId},
          ),
        )),
      ) as _i7.Future<_i3.UserRank>);

  @override
  _i7.Future<List<_i3.TopCreator>> getTopCreators({
    _i6.LeaderboardPeriod? period = _i6.LeaderboardPeriod.weekly,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopCreators,
          [],
          {
            #period: period,
            #limit: limit,
          },
        ),
        returnValue: _i7.Future<List<_i3.TopCreator>>.value(<_i3.TopCreator>[]),
      ) as _i7.Future<List<_i3.TopCreator>>);

  @override
  _i7.Future<_i2.PaginatedResponse<_i3.LeaderboardEntry>>
      getFriendsLeaderboard({
    required String? challengeId,
    int? page = 1,
    int? limit = 20,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getFriendsLeaderboard,
              [],
              {
                #challengeId: challengeId,
                #page: page,
                #limit: limit,
              },
            ),
            returnValue:
                _i7.Future<_i2.PaginatedResponse<_i3.LeaderboardEntry>>.value(
                    _FakePaginatedResponse_0<_i3.LeaderboardEntry>(
              this,
              Invocation.method(
                #getFriendsLeaderboard,
                [],
                {
                  #challengeId: challengeId,
                  #page: page,
                  #limit: limit,
                },
              ),
            )),
          ) as _i7.Future<_i2.PaginatedResponse<_i3.LeaderboardEntry>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i8.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<(_i4.User, _i5.AuthTokens)> socialLogin({
    required String? provider,
    required String? idToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #socialLogin,
          [],
          {
            #provider: provider,
            #idToken: idToken,
          },
        ),
        returnValue: _i7.Future<(_i4.User, _i5.AuthTokens)>.value((
          _FakeUser_2(
            this,
            Invocation.method(
              #socialLogin,
              [],
              {
                #provider: provider,
                #idToken: idToken,
              },
            ),
          ),
          _FakeAuthTokens_3(
            this,
            Invocation.method(
              #socialLogin,
              [],
              {
                #provider: provider,
                #idToken: idToken,
              },
            ),
          )
        )),
      ) as _i7.Future<(_i4.User, _i5.AuthTokens)>);

  @override
  _i7.Future<(_i4.User, _i5.AuthTokens)> devLogin({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #devLogin,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i7.Future<(_i4.User, _i5.AuthTokens)>.value((
          _FakeUser_2(
            this,
            Invocation.method(
              #devLogin,
              [],
              {
                #email: email,
                #password: password,
              },
            ),
          ),
          _FakeAuthTokens_3(
            this,
            Invocation.method(
              #devLogin,
              [],
              {
                #email: email,
                #password: password,
              },
            ),
          )
        )),
      ) as _i7.Future<(_i4.User, _i5.AuthTokens)>);

  @override
  _i7.Future<_i5.AuthTokens> refreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [refreshToken],
        ),
        returnValue: _i7.Future<_i5.AuthTokens>.value(_FakeAuthTokens_3(
          this,
          Invocation.method(
            #refreshToken,
            [refreshToken],
          ),
        )),
      ) as _i7.Future<_i5.AuthTokens>);

  @override
  _i7.Future<_i4.User> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i7.Future<_i4.User>.value(_FakeUser_2(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i7.Future<_i4.User>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [SocialLoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialLoginUseCase extends _i1.Mock
    implements _i9.SocialLoginUseCase {
  MockSocialLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<(_i4.User, _i5.AuthTokens)> call({
    required String? provider,
    required String? idToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #provider: provider,
            #idToken: idToken,
          },
        ),
        returnValue: _i7.Future<(_i4.User, _i5.AuthTokens)>.value((
          _FakeUser_2(
            this,
            Invocation.method(
              #call,
              [],
              {
                #provider: provider,
                #idToken: idToken,
              },
            ),
          ),
          _FakeAuthTokens_3(
            this,
            Invocation.method(
              #call,
              [],
              {
                #provider: provider,
                #idToken: idToken,
              },
            ),
          )
        )),
      ) as _i7.Future<(_i4.User, _i5.AuthTokens)>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i10.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i11.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> saveTokens(_i5.AuthTokens? tokens) => (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [tokens],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.AuthTokens?> getTokens() => (super.noSuchMethod(
        Invocation.method(
          #getTokens,
          [],
        ),
        returnValue: _i7.Future<_i5.AuthTokens?>.value(),
      ) as _i7.Future<_i5.AuthTokens?>);

  @override
  _i7.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> hasTokens() => (super.noSuchMethod(
        Invocation.method(
          #hasTokens,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> saveUser(_i12.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearUser() => (super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool isOnboardingCompleted() => (super.noSuchMethod(
        Invocation.method(
          #isOnboardingCompleted,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> setOnboardingCompleted() => (super.noSuchMethod(
        Invocation.method(
          #setOnboardingCompleted,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
