import type { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';

export async function seed(knex: Knex): Promise<void> {
  await knex('coin_packages').del();

  await knex('coin_packages').insert([
    {
      id: uuidv4(),
      name: '100 Sparks',
      coin_amount: 100,
      bonus_amount: 0,
      price_usd: 0.99,
      apple_product_id: 'sparks_100',
      google_product_id: 'sparks_100',
      is_best_value: false,
      is_active: true,
      sort_order: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name: '550 Sparks',
      coin_amount: 500,
      bonus_amount: 50,
      price_usd: 4.99,
      apple_product_id: 'sparks_550',
      google_product_id: 'sparks_550',
      is_best_value: false,
      is_active: true,
      sort_order: 2,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name: '1200 Sparks',
      coin_amount: 1000,
      bonus_amount: 200,
      price_usd: 9.99,
      apple_product_id: 'sparks_1200',
      google_product_id: 'sparks_1200',
      is_best_value: true,
      is_active: true,
      sort_order: 3,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name: '2500 Sparks',
      coin_amount: 2000,
      bonus_amount: 500,
      price_usd: 19.99,
      apple_product_id: 'sparks_2500',
      google_product_id: 'sparks_2500',
      is_best_value: false,
      is_active: true,
      sort_order: 4,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name: '7500 Sparks',
      coin_amount: 5000,
      bonus_amount: 2500,
      price_usd: 49.99,
      apple_product_id: 'sparks_7500',
      google_product_id: 'sparks_7500',
      is_best_value: false,
      is_active: true,
      sort_order: 5,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);
}
